services:
  zynq-builder:
    image: zynq-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: zynq-builder
    working_dir: /workspace/fpga-fa
    volumes:
      - ../..:/workspace/fpga-fa
    command: ["sleep", "infinity"]
    tty: true
    stdin_open: true
